name = "victie-monitor-backend"
main = "server.ts"
compatibility_date = "2024-04-01"
compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "DB"
database_name = "victie-monitor-db"
database_id = "e654d1c1-a250-4f57-acc2-cfbac6bf91bd" # Ganti dengan ID hasil dari perintah 'wrangler d1 create'

[triggers]
crons = [ "* * * * *" ]

[vars]
JWT_SECRET = "RAHASIA_SUPER_AMAN_DEV_ONLY"
DISCORD_WEBHOOK_URL = ""
TELEGRAM_BOT_TOKEN = ""
TELEGRAM_CHAT_ID = ""
